FROM nginx:alpine

COPY infrastructure/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/
COPY research/index.html /usr/share/nginx/html/research/
COPY benchmark/index.html /usr/share/nginx/html/benchmark/
COPY admin/index.html /usr/share/nginx/html/admin/
COPY profiles/Performance.mobileconfig /usr/share/nginx/html/profiles/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
